

[profiles.Desk_mono]
config_file = "/home/zyr/.dotfiles/modules/home/hyprdynamicmonitors/tmp/hyprconfigs/Desk_mono.go.tmpl"
config_file_type = "template"
[profiles.Desk_mono.conditions]

[[profiles.Desk_mono.conditions.required_monitors]]
description = "BOE NE160QDM-NZ6"
monitor_tag = "monitor0"

[[profiles.Desk_mono.conditions.required_monitors]]
description = "BNQ BenQ RD280UA E3S0031901Q"
monitor_tag = "monitor1"
